### ISSUE TITLE
Release code and checkpoints.

### ISSUE THREAD

**Issue by Dibbidy** [ByteFlow-AI/TokenFlow#1]
Could you please release the model checkpoints for the tokenizer, text-to-image model, and multimodal understanding model, as well as the training and inference code for the tokenizer, text-to-image generation, and multimodal understanding? Additionally, it would be great to have the single-scale version of TokenFlow available. These components would be incredibly helpful. Thank you!

**Comment by QuLiao1117** [comment]
Thank you for your interest in our work! All codes and checkpoints will be released in one week.

**Comment by QuLiao1117** [comment]
Code and checkpoints released, closing this issue.
