### ISSUE TITLE
Sharing GenAI-Bench

### ISSUE THREAD

**Issue by linzhiqiu** [ByteFlow-AI/TokenFlow#4]
Just wanted to share some other related work on robust benchmarking of T2I generation:

1 - [VQAScore](https://linzhiqiu.github.io/papers/vqascore/): VQAScore is a simple but effective automated scoring metric for image-text alignment. VQAScore strongly agrees with human judgments on compositional text prompts and can be run using one-line Python code in our repo [here](https://github.com/linzhiqiu/t2v_metrics)! It also significantly outperforms previous automated metrics such as ImageReward, HPSv2, and PickScore. Google's [Imagen3](https://arxiv.org/abs/2408.07009) reported VQAScore as the strongest replacement for CLIPScore.
2 - [GenAI-Bench](https://linzhiqiu.github.io/papers/genai_bench/): We introduce a comprehensive benchmark for compositional image generation with 1,600 prompts written by professional designers. We also show that VQAScore can be used as a strong reward metric by re-ranking the generated candidate images. GenAI-Bench was presented as the Best Short Paper at SynData@CVPR24 workshop and was highlighted in Imagen3's report.

Best,
Zhiqiu

**Comment by QuLiao1117** [comment]
Thanks for sharing these useful benchmarks, they will help a lot for the T2I community.
