### ISSUE TITLE
About train strategy

### ISSUE THREAD

**Issue by Doctor-James** [ByteFlow-AI/TokenFlow#5]
Thank you for your excellent work. I have a question regarding your training strategy. From the code, it seems that you train the C2I and I2C tasks separately. This appears to differ from previous approaches that trained the tasks jointly. How do you ensure that the two training tasks do not interfere with each other? For example, could training the generation task lead to a loss of understanding capabilities?
Or is the core contribution of this paper to provide a unified tokenizer, with downstream tasks trained separately, rather than enabling simultaneous understanding and generation?

**Comment by QuLiao1117** [comment]
Yes, the core contribution of this paper to provide a unified tokenizer, with different downstream tasks verified separately.
