### ISSUE TITLE
Some questions bout 3.2. Unified Image Tokenizer

### ISSUE THREAD

**Issue by Lwt-diamond** [ByteFlow-AI/TokenFlow#6]
Hi, I noticed that you used a dual-encoder architecture with a semantic encoder initialized using a pre-trained vision encoder (e.g., CLIP ViT-B/14). Could you clarify what initialization method is used for the pixel encoder (Epix)? Thanks!

![image](https://github.com/user-attachments/assets/60abe411-c920-470d-910d-c3eb20b20ec0)

**Comment by QuLiao1117** [comment]
Thanks for raising this question, we do not use special initialization for pixel encoder. This can be found in https://github.com/ByteFlow-AI/TokenFlow/blob/main/tokenflow/tokenizer/vq_model.py#L90
