### ISSUE TITLE
Some question about the motivation?

### ISSUE THREAD

**Issue by FacePoluke** [ByteFlow-AI/TokenFlow#9]
Why use shared indices? What are the disadvantages if I simply concatenate semantic features and pixel features and use a single codebook?

**Comment by QuLiao1117** [comment]
> Why use shared indices? What are the disadvantages if I simply concatenate semantic features and pixel features and use a single codebook?

The key insight is to calculate the weighted distance to find the optimal index. If you are considering changing two nn.Embedding into one concated nn.Embedding and performing the same operation, that's definitely okay. It's just a different way to implement the same idea.
